### ISSUE TITLE
Upgrade gem to support Rails 7

### ISSUE THREAD

**Issue by geetfun** [mainio/ratonvirus#18]
@ahukkanen I noticed that the gem is not currently compatible with Rails 7 and performed a version bump on my own fork. I've created a PR to bump the dependencies: https://github.com/mainio/ratonvirus/pull/17.

Please check it out, thanks!

**Comment by ahukkanen** [comment]
It's now released:
https://github.com/mainio/ratonvirus/releases/tag/v0.4.0
https://rubygems.org/gems/ratonvirus/versions/0.4.0

Thank you again!
