### ISSUE TITLE
Manual scan is not working

### ISSUE THREAD

**Issue by railsfactory-krishnaveni** [mainio/ratonvirus#32]
This is for an awesome gem for auto scanning. I use this gem for an RoR application. I am using carrierwave. so auto scanning is working. I would like to do a manual scanning where the system does not have mount_uploader for a specific model.

Here is what I tried by giving the path of the file and and file as well and I am getting undefined method error for one scenario and I am getting "true" for the virus check for another scenario where the file does not have virus.

f = File.new(tempfile_path)
Ratonvirus.scanner.available? && Ratonvirus.scanner.virus?(f)

NoMethodError: undefined method `empty?' for #<File:0x00009x>

=================

tempfile_path = params[:attachment].tempfile
Ratonvirus.scanner.available? && Ratonvirus.scanner.virus?(tempfile_path)

NoMethodError: undefined method `empty?' for #<Tempfile:0x007ff568248a50>

=================
Ratonvirus.scanner.available? && Ratonvirus.scanner.virus?(tempfile_path.path)
=> true

=================
Could you please check this issue and help me to solve it.
Thank you.

**Comment by araccaine** [comment]
I can reproduce the issue:

- `Ratonvirus.scanner.virus?(File.new('some_existing_filepath'))`
    - gives `undefined method 'empty?' for #File:xxx`
- `Ratonvirus.scanner.virus?(File.new('some_existing_filepath').path)`
    - gives `false`
- `Ratonvirus.scanner.virus?('some_filepath_that_does_not_exist')`
    - gives `true` but should actually raise some error (file not found or whatever)

**Comment by ahukkanen** [comment]
This has been fixed in the [latest release 0.4.3](https://github.com/mainio/ratonvirus/releases/tag/v0.4.3) which is pushed to RubyGems.
